<?php

/**
 * Islandora audio solution pack module
 */

/**
 * Islandora audio solution pack required fedora objects
 * @return type 
 */
function islandora_audio_sp_required_fedora_objects() {
  module_load_include('inc', 'fedora_repository', 'fedora_repository.solutionpacks');
  $module_path = drupal_get_path('module', 'islandora_audio_sp');
  $islandora_path = drupal_get_path('module', 'fedoroa_repository');
  $form_name = 'Islandora Audio MODS Form';
  $form_xml = file_get_contents("$module_path/xml/mods_audio.xml");
  solution_pack_add_form($form_name, $form_xml);
  solution_pack_add_form_association('islandora:sp-audioCModel', $form_name);

  return array(
    'islandora_audio_sp' => array(
      'module' => 'islandora_audio_sp',
      'title' => 'Islandora Audio Solution Pack',
      'objects' => array(
        array(
          'foxml_file' => "$module_path/xml/islandora_sp_audioCModel.xml",
          'pid' => 'islandora:sp-audioCModel',
          'dsid' => NULL,
          'datastream_file' => NULL,
          'dsversion' => NULL,
        ),
        array(
          'pid' => 'islandora:audio_collection',
          'label' => 'Audio Collection',
          'cmodel' => 'islandora:collectionCModel',
          'parent' => 'islandora:root',
          'datastreams' => array(
            array(
              'dsid' => 'COLLECTION_POLICY',
              'datastream_file' => "$module_path/xml/audio_collection_policy.xml",
            ),
            array(
              'dsid' => 'TN',
              'datastream_file' => "$module_path/images/Crystal_Clear_filesystem_folder_grey.png",
              'mimetype' => 'image/png',
            ),
          ),
        ),
      ),
    ),
  );
}

