<?php

// $Id$


function islandora_audio_sp_required_fedora_objects() {


  $module_path = drupal_get_path('module', 'islandora_audio_sp');

  // array( 'path-to-foxml-file', 'pid', 'dsid', 'path-to-datastream-file', int dsversion, boolean required)
  // make database insertions here.

  // Put the form in the database
  $result = db_result(db_query('Select name from {xml_forms} where name = "%s"', 'Islandora Audio MODS Form'));
  if (!$result) {
    $filename = "$module_path/xml/mods_audio.xml";
    $form_as_string = file_get_contents($filename);
    $object = new stdClass();
    $object->name = 'Islandora Audio MODS Form';
    $object->form = $form_as_string;
    $result = drupal_write_record('xml_forms', $object);
  }

  // Associates the form with the content model
  $result = db_result(db_query('Select content_model from {islandora_content_model_forms} where  content_model = "%s" and form_name = "%s"', 'islandora:sp-audioCModel', 'Islandora Audio MODS Form'));
  if (!$result) {
    $object = new stdClass();
    $object->content_model = 'islandora:sp-audioCModel';
    $object->form_name = 'Islandora Audio MODS Form';
    $object->dsid = 'MODS';
    $object->title_field = "['titleInfo']['title']";
    $object->transform = 'mods_to_dc.xsl';
    $result = drupal_write_record('islandora_content_model_forms', $object);
  }

  return array(
    'islandora_audio_sp' => array(
      'module' => 'slandora_audio_sp',
      'title' => 'Islandora Audio Solution Pack',
      'objects' => array(
        array(
          'foxml_file' => "$module_path/xml/islandora_sp_audioCModel.xml",
          'pid' => 'islandora:sp-audioCModel',
          'dsid' => NULL,
          'datastream_file' => NULL,
          'dsversion' => NULL,
        ),

        array(
          'pid' => 'islandora:audio_collection',
          'label' => 'Audio Collection',
          'cmodel' => 'islandora:collectionCModel',
          'parent' => 'islandora:top',
          'datastreams' => array(
            array(
              'dsid' => 'COLLECTION_POLICY',
              'datastream_file' => "$module_path/xml/audio_collection_policy.xml",
            ),
            array(
              'dsid' => 'TN',
              'datastream_file' => "$module_path/images/audio-TN.jpg",
              'mimetype' => 'image/png',
            ),
          ),
        ),
      ),
    ),
  );
}

